apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
spec:
  interval: 10m0s
  timeout: 2m0s
  sourceRef:
    kind: GitRepository
    name: tenant-repository
  path: ./apps/podinfo
  prune: true
  force: true
  wait: true